version: '3.8'
services:
    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: nestjs-api
        networks:
            - freecodecamp

    nestjs-api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3333:3333
        networks:
            - freecodecamp

networks:
    freecodecamp:
