version: "3.8"
services:
    app:
        build:
            context: .
            target: development
        container_name: nestjs
        volumes:
            - .:/usr/src/app
            - node_modules:/usr/src/app/node_modules
        ports:
            - 3000:3000
            # - 9229:9229
        env_file:
            - .env
        networks:
            - freecodecamp
        depends_on:
            - dev-db

    dev-db:
        image: postgres:latest
        container_name: dev-db
        volumes:
            - dev-db:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Postgres7!
            POSTGRES_DB: nestjs
            # PG_DATA: /var/lib/postgresql/data
        networks:
            - freecodecamp

    test-db:
        image: postgres:latest
        container_name: test-db
        volumes:
            - test-db:/var/lib/postgresql/data
        ports:
            - 2345:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Postgres7!
            POSTGRES_DB: nestjs
            # PG_DATA: /var/lib/postgresql/data
        networks:
            - freecodecamp

volumes:
    dev-db:
    test-db:
    node_modules:

networks:
    freecodecamp:
        name: freecodecamp
        external: true
