version: "3.8"
services:
    app:
        build:
            context: .
            target: development
        container_name: nestjs
        command: yarn start:debug
        # network_mode: service:dev-db
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3333:3333
            - 9229:9229
        env_file:
            - .env
        networks:
            - freecodecamp
        depends_on:
            - dev-db

    dev-db:
        image: postgres:latest
        container_name: dev-db
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Postgres7!
            POSTGRES_DB: nestjs-api
            PG_DATA: /var/lib/postgresql/data
        networks:
            - freecodecamp

    test-db:
        image: postgres:latest
        container_name: test-db
        ports:
            - 5431:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Postgres7!
            POSTGRES_DB: nestjs-api-test
        networks:
            - freecodecamp

networks:
    freecodecamp:
        name: freecodecamp
        external: true
volumes:
    pgdata:
