version: '3.8'
services:
    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: fcc-nestjs-api
        networks:
            - freecodecamp

networks:
    freecodecamp:
